import Head from "next/head";
import styles from "../styles/Home.module.css";
import { read, utils } from "xlsx";

export default function Home() {
  const readUploadFile = (e) => {
    e.preventDefault();
    if (e.target.files) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const data = e.target.result;
        const workbook = read(data, { type: "array" });
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        const json = utils.sheet_to_json(worksheet);
        document.getElementById("json").textContent = JSON.stringify(json, undefined, 2);
      };
      reader.readAsArrayBuffer(e.target.files[0]);
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <form>
          <label htmlFor='upload'>Upload File</label>
          <input type='file' name='upload' id='upload' accept='.xlsx, .xls' required onChange={readUploadFile} />
          <br />
          <br />
          <br />
          <pre id='json'></pre>
        </form>
      </main>
    </>
  );
}
